# Mount Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Load dataset

In [4]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Financial_News_Sentiment_Prediction_using_DeepLearning/sent_train.csv")
print(data.head())
data_test=pd.read_csv("/content/drive/MyDrive/Financial_News_Sentiment_Prediction_using_DeepLearning/sent_valid.csv")
print(data_test.head())

                                                text  label
0  $BYND - JPMorgan reels in expectations on Beyo...      0
1  $CCL $RCL - Nomura points to bookings weakness...      0
2  $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3  $ESS: BTIG Research cuts to Neutral https://t....      0
4  $FNKO - Funko slides after Piper Jaffray PT cu...      0
                                                text  label
0  $ALLY - Ally Financial pulls outlook https://t...      0
1  $DELL $HPE - Dell, HPE targets trimmed on comp...      0
2  $PRTY - Moody's turns negative on Party City h...      0
3                   $SAN: Deutsche Bank cuts to Hold      0
4                  $SITC: Compass Point cuts to Sell      0

In [6]:
print(data['label'].unique())
print(data_test['label'].unique())

[0 1 2]
[0 1 2]

# Data exploration

In [7]:
# Display the shape of the DataFrame
print(f"Shape of the train dataframe: {data.shape}")
print(f"Shape of the train dataframe: {data_test.shape}")

Shape of the train dataframe: (9543, 2)
Shape of the train dataframe: (2388, 2)

In [8]:
# Display value counts for the 'label' column
print("Value counts for 'label' column:")
print(data['label'].value_counts())
print(data_test['label'].value_counts())

Value counts for 'label' column:
label
2    6178
1    1923
0    1442
Name: count, dtype: int64
label
2    1566
1     475
0     347
Name: count, dtype: int64

In [9]:
#check for missing values in the DataFrame
print(data.isnull().sum())
print(data_test.isnull().sum())

text     0
label    0
dtype: int64
text     0
label    0
dtype: int64

In [10]:
#check for duplicate rows in the DataFrame
print("Duplicate rows:", data.duplicated().sum())
print("Duplicate rows:", data_test.duplicated().sum())

Duplicate rows: 0
Duplicate rows: 0

# Data preprocessing

## Text cleaning

In [11]:
import unicodedata
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [12]:
# Keep important negation words
negation_words = {'not', 'no', 'never', 'neither', 'nor'}
stop_words = stop_words - negation_words


def clean_text(text):

    # Convert to string
    text = str(text)

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Convert to lowercase
    text = text.lower()

    # Split into words
    text = text.split()

    # Remove stopwords but keep negation words
    text = [word for word in text if word not in stop_words]

    # Convert list back to string
    text = " ".join(text)

    return text

In [13]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [14]:
data["clean_text"] = data["text"].apply(clean_text)

In [15]:
data_test["clean_text"] = data["text"].apply(clean_text)

In [16]:
data[["text", "clean_text"]].head()

,text,clean_text
0,$BYND - JPMorgan reels in expectations on Beyo...,bynd jpmorgan reels expectations beyond meat h...
1,$CCL $RCL - Nomura points to bookings weakness...,ccl rcl nomura points bookings weakness carniv...
2,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",cx cemex cut credit suisse jp morgan weak buil...
3,$ESS: BTIG Research cuts to Neutral https://t....,ess btig research cuts neutral httpstcomcyftsxcn
4,$FNKO - Funko slides after Piper Jaffray PT cu...,fnko funko slides piper jaffray pt cut httpstc...

In [17]:
data_test[["text", "clean_text"]].head()

,text,clean_text
0,$ALLY - Ally Financial pulls outlook https://t...,bynd jpmorgan reels expectations beyond meat h...
1,"$DELL $HPE - Dell, HPE targets trimmed on comp...",ccl rcl nomura points bookings weakness carniv...
2,$PRTY - Moody's turns negative on Party City h...,cx cemex cut credit suisse jp morgan weak buil...
3,$SAN: Deutsche Bank cuts to Hold,ess btig research cuts neutral httpstcomcyftsxcn
4,$SITC: Compass Point cuts to Sell,fnko funko slides piper jaffray pt cut httpstc...

In [18]:
print("Original text nulls:", data["text"].isna().sum())
print("Clean text nulls:", data["clean_text"].isna().sum())

print(data[data["clean_text"].isna()][["text", "clean_text"]].head(10))

Original text nulls: 0
Clean text nulls: 0
Empty DataFrame
Columns: [text, clean_text]
Index: []

In [19]:
print("Original text nulls:", data_test["text"].isna().sum())
print("Clean text nulls:", data_test["clean_text"].isna().sum())

print(data_test[data_test["clean_text"].isna()][["text", "clean_text"]].head(10))

Original text nulls: 0
Clean text nulls: 0
Empty DataFrame
Columns: [text, clean_text]
Index: []

# Saving the cleaning data

In [20]:
data.to_csv("/content/drive/MyDrive/Financial_News_Sentiment_Prediction_using_DeepLearning/cleaned.csv",index=False)
data_test.to_csv("/content/drive/MyDrive/Financial_News_Sentiment_Prediction_using_DeepLearning/cleaned_test.csv",index=False)